#!/usr/bin/env bash

set -e
set -u

function run {
    (start=$(date +%s%N); "$@" &> last_log.log && stop=$(date +%s%N) && time=$(echo "scale=4 ; $(((stop-start))) / 1000000000.0" | bc) && echo "[ OK ] (${time}s) $*") || ( echo "[ FAILED ] $*" ; cat last_log.log ; exit 1 )
}

if [ $# -lt 5 ]
then
  echo "usage: $0 <niter> <sigma> <sourcefile> <targetfile> <output_transfo> [<minctracc_options>]"
  exit 1
fi

# TODO: improve option parsing
niter=$1
sigma=$2
shift
shift
sourcefile=$1
targetfile=$2
output_transfo=$3

sourcenifti="$(basename ${sourcefile} .mnc).nii"
tempsource="temp_source.nii"
tempsourcemnc="temp_source.mnc"

shift

run mnc2nii ${sourcefile} ${sourcenifti}

transfos=""
for i in $(seq 1 ${niter})
do
  echo
  echo "> Iteration $i"
  run gauss.py ${sourcenifti} ${tempsource} ${sigma}
  run rm -f ${tempsourcemnc}
  run nii2mnc ${tempsource} ${tempsourcemnc}
  run minctracc ${tempsourcemnc} $* # see 'shift' above
  bak_transfo="$(basename ${output_transfo} .xfm).${i}.xfm"
  run cp ${output_transfo} ${bak_transfo}
  transfos="${transfos} ${bak_transfo}"
  
  # Average transformations
  run mean_transfos.py ${transfos} ${output_transfo}
  # Get variance  
  var=$(grep mean last_log.log | awk -F ';' '{print $2}' | awk '{print $NF}')
  echo "Variance: $var"
done

